server:
  port: 8080
# ... 其他配置 ...
system:
  register:
    enabled: true  # 控制是否开放注册功能

spring:
  main:
    # 关闭banner
    banner-mode: off
    # 允许循环引用
    allow-circular-references: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-prod.yaml
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 连接池管理
  data:
    redis:
      cluster:
        nodes: 172.20.0.9:6381,172.20.0.10:6382, 172.20.0.11:6383, 172.20.0.12:6384, 172.20.0.13:6385, 172.20.0.14:6386
        max-redirects: 3
      password: 123456
#      database: 0
#      host: 172.18.0.4
#      port: 6379
#      password: 8IApxf6i3K4oPnt6zOUXyR4hiN24YpNPXWD3
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0


  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  global-config:
    # 关闭banner
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case:
  type-aliases-package: cn.org.alan.exam.model

jwt:
  secret: 47EQ7VKDBvOufw5PWhtTaOTORKrzaUVAitduSVFvK862kkx2TIHH4xNtVih8SH0V56fS4S7ff0VfqVZPaonWdR3N1t8eE2f2CPeL

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com"
  access-key-id: LTAI5tGaZUEhWr9Jg3EUC9FQ
  access-key-secret: 4hFcObCh2ArA0wZZYbBP9mRy4BD2NO
  bucket-name: online-exam-system-backend

common:
  adminId: 1

logging:
  level:
    root: info
    com.example: debug
  file:
    name: ./logs/exam.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 1GB
      max-history: 7