server:
  port: 8080
# ... 其他配置 ...
system:
  register:
    enabled: true  # 控制是否开放注册功能

spring:
  main:
    # 关闭banner
    banner-mode: off
    # 允许循环引用
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_exam?useSSL=false&serverTimezone=UTC
    username: root
    password: Aa112211
    driver-class-name: com.mysql.cj.jdbc.Driver

    # druid 连接池管理
  data:
    redis:
#      cluster:
#        nodes: 127.0.0.1:6381,127.0.0.1:6382, 127.0.0.1:6383, 127.0.0.1:6384, 127.0.0.1:6385, 127.0.0.1:6386
#        max-redirects: 3
#      password: 123456
      database: 0
      host: 127.0.0.1
      port: 6379
      password: Aa112211
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0


  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  global-config:
    # 关闭banner
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case:
  type-aliases-package: cn.org.alan.exam.model

jwt:
  secret: 47EQ7VKDBvOufw5PWhtTaOTORKrzaUVAitduSVFvK862kkx2TIHH4xNtVih8SH0V56fS4S7ff0VfqVZPaonWdR3N1t8eE2f2CPeL

oss:
  endpoint: https://oss-cn-beijing.aliyuncs.com
  access-key-id: LTAI5tGaZUEhWr9Jg3EUC9FQ
  access-key-secret: 4hFcObCh2ArA0wZZYbBP9mRy4BD2NO
  bucket-name: online-exam-system-backend


minio:
  endpoint: http://127.0.0.1:9000 # minio服务地址
  accesskey: admin # minio用户名
  secretKey: 12345678 # minio密码
  bucket: online-exam #桶名

logging:
  level:
    root: info
    com.example: debug
common:
  adminId: 1

#自定义配置
online-exam:
  storage:
    type: aliyun # 存储方式的配置 aliyun、minio
  login:
    captcha:
      enabled: true #是否启用验证码登录
