server:
  port: 8080

spring:
  main:
    # 关闭banner
    banner-mode: off
    # 允许循环引用
    allow-circular-references: true
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-dev.yaml
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 连接池管理
  data:
    redis:
      cluster:
        nodes:
        max-redirects: 3
#      database: 0
#      host: ${redishost}
#      port: 6379
#      password: ${redispassword}
#      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数 默认8 ，负数表示没有限制
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
          max-wait: -1
          # 连接池中的最大空闲连接 默认8
          max-idle: 8
          # 连接池中的最小空闲连接 默认0
          min-idle: 0

  servlet:
    multipart:
      max-file-size: 5MB

mybatis-plus:
  global-config:
    # 关闭banner
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case:
  type-aliases-package: cn.org.alan.exam.model

jwt:
  secret: ${jwtsecret}

oss:
  endpoint: ${ossendpoint}
  access-key-id: ${AccessKeyID}
  access-key-secret: ${AccessKeySecret}
  bucket-name: ${ossbucketname}

logging:
  level:
    root: info
    com.example: debug
common:
  adminId: 1
